language: clojure
lein: lein2
before_install: git clone https://github.com/technomancy/leiningen.git lein && cd lein && git checkout 2.1.2 && cd leiningen-core && lein2 bootstrap && cd ..
script: cd .. && lein/bin/lein run
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
notifications:
  irc: "irc.freenode.org#swearjure"
